FROM node:22-alpine AS builder
LABEL authors="Anders Sund-Jensen"
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY environment/docker-setup/nginx/nginx.conf /etc/nginx/conf.d/default.conf

