package com.sundtrack.catan.datalayer.domain.exceptions.validation;

public enum ValidationErrorCode {
    NOT_PLAYERS_TURN,
    DISTANCE_RULE_VIOLATED,
    ILLEGAL_ACTION_IN_GAME_PHASE,
    VERTEX_IS_OCCUPIED,
    EDGE_IS_OCCUPIED,
    NO_CONNECTED_ROAD_VIOLATED,
    INSUFFICIENT_RESOURCES,
    PLAYER_NOT_FOUND,
    SETTLEMENT_OWNED_BY_DIFFERENT_PLAYER,
    NO_SETTLEMENT_TO_UPGRADE,
    ALREADY_CITY,
    NO_TILE_ON_HEX,
    TILE_ALREADY_ROBBED,
    INVALID_HEX,
    PLAYER_NOT_PENDING_DISCARD,
    INVALID_DISCARD_COUNT,
    RESOURCE_NOT_OWNED,
    INSUFFICIENT_BANK_RESOURCES,
    INSUFFICIENT_DEVELOPMENT_CARDS,
    NO_BUILDING_LEFT,
    INVALID_STEAL_PLAYER,
    INTERNAL_ERROR
}
