spring.application.name=Hexa
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
game-snapshot.base-path=src/main/resources/snapshot/game
# SQLite Datasource Configuration
spring.datasource.url=jdbc:sqlite:catan_games.db
spring.datasource.driver-class-name=org.sqlite.JDBC
# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false